# Generated by Django 5.0.2 on 2024-03-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image_src', models.URLField()),
                ('image_alt', models.CharField(max_length=400)),
                ('duration', models.CharField(max_length=400)),
                ('rate', models.CharField(max_length=400)),
                ('votes', models.CharField(max_length=600)),
            ],
        ),
    ]
